--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make-Zip
version:             1.02
abstract:            CPAN Test Dummy for CPAN.pm
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              ~
distribution_type:   module
requires:     
    CPAN::Test::Dummy::Perl5::Make: 0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
