--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make-Zip
version:             1.03
abstract:            CPAN Test Dummy for CPAN.pm
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    CPAN::Test::Dummy::Perl5::Make: 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
